version: "3.8"
services:
    thumbnailer:
        build: ./thumbnail-server
        ports: 
            - "5000:5000"
        networks:
            - frontend
            - backend
    resizer:
        build: ./resize-server
        networks:
            - backend
networks:
    frontend:

    backend:
